export default {
  GEOGRAFIA: {
    TERRENO: [
      "Deserto",
      "Floresta",
      "Montanhas",
      "Planícies",
      "Ilhas",
      "Pântanos",
      "Tundra",
      "Selva",
      "Cânion",
      "Planalto",
    ],
    CLIMA: [
      "Tropical (Quente e úmido com chuvas frequentes)",
      "Temperado (Estações distintas com invernos frios e verões quentes)",
      "Árido (Seco e quente com pouca chuva)",
      "Polar (Extremamente frio e com neve)",
      "Subtropical (Quente, mas com invernos mais amenos)",
      "Continental (Invernos frios e verões quentes, sem influência marítima)",
      "Equatorial (Quente, úmido e com chuvas frequentes durante o ano todo)",
      "Mediterrâneo (Invernos suaves, verões quentes e estação chuvosa no inverno)",
      "Desértico (Extremamente seco e quente durante o dia, frio à noite)",
      "Montanhoso (Variações de temperatura de acordo com a altitude)",
      "Oceânico (Invernos suaves e verões amenos com chuvas regulares)",
      "Continental Extremo (Invernos muito frios e verões muito quentes)",
    ],
    CARACTERISTICA: [
      "Vulcão ativo",
      "Cidade flutuante nas nuvens",
      "Cavernas gigantes habitadas por criaturas subterrâneas",
      "Cidade submersa nas profundezas do oceano",
      "Planície de cristais gigantes",
      "Pico de montanha que toca o céu",
      "Árvores gigantes que se comunicam entre si",
      "Geiser de água quente",
      "Desfiladeiro estreito e sinuoso",
      "Ponte de pedra natural que atravessa um rio poderoso",
      "Lago de água cristalina com propriedades mágicas",
      "Floresta encantada com árvores que se movem",
      "Ruínas antigas de uma civilização perdida",
      "Grande fenda subterrânea com caminhos interligados",
      "Lago de lama borbulhante",
      "Monumentos de pedra gigantes esculpidos por uma antiga civilização",
      "Campos magnéticos que afetam a bússola",
      "Rochas flutuantes em um pântano",
      "Campo de flores mágicas que mudam de cor com o clima",
      "Labirinto natural de passagens subterrâneas",
    ],
  },
  SOCIEDADE: {
    TIPO_SOCIEDADE: [
      "Feudal (Sociedade estratificada com nobreza, servos e cavaleiros)",
      "Tribal (Comunidades organizadas em clãs ou tribos)",
      "Democrática (Governo com eleições e participação popular)",
      "Anárquica (Ausência de governo centralizado, com autonomia local)",
      "Teocrática (Governo baseado na religião e liderado por líderes religiosos)",
      "Mercantil (Sociedade focada no comércio e nas guildas)",
      "Mágica (Sociedade em que a magia desempenha um papel central)",
      "Totalitária (Governo autoritário com controle rígido sobre a população)",
    ],
    DOMINANTE: [
      "Humanos",
      "Elfos",
      "Anões",
      "Orcs",
      "Gnomos",
      "Raça Personalizada (ou uma raça específica do seu mundo)",
    ],
    POLITICA: [
      "Monarquia absoluta (um rei ou rainha tem poder total)",
      "Monarquia constitucional (um monarca com poderes limitados por uma constituição)",
      "República democrática (governo eleito pelo povo)",
      "Oligarquia (um pequeno grupo de elite controla o governo)",
      "Teocracia (líderes religiosos controlam o governo)",
      "Federação de estados independentes (vários estados com governo próprio unidos sob um governo federal)",
      "Confederação (várias nações independentes se unem para objetivos comuns, mas mantêm autonomia)",
      "Anarquia (ausência de governo centralizado)",
      "Ditadura (um líder autoritário tem poder absoluto)",
      "Governo tribal (liderança baseada em conselhos de anciãos ou chefes de tribos)",
    ],
    PREDOMINANTE: [
      "Humanos",
      "Elfos",
      "Anões",
      "Orcs",
      "Gnomos",
      "Halflings",
      "Tieflings",
      "Draconatos",
      "Meio-elfos",
      "Meio-orcs",
      "Genasi",
      "Raça Personalizada (ou uma raça específica do seu mundo)",
    ],
    RELACOES: [
      "Aliança de longa data (as raças cooperam há gerações)",
      "Tensão diplomática (relações diplomáticas instáveis)",
      "Guerra fria (paz, mas com desconfiança mútua)",
      "Guerra em andamento (as raças estão em conflito ativo)",
      "Tratado de não agressão (paz frágil, com acordo de não agressão)",
      "Relações comerciais fortes (as raças prosperam através do comércio)",
      "Relações comerciais limitadas (acordos comerciais esporádicos)",
      "Casamentos inter-raciais comuns (mistura de sangue comum)",
      "Preconceito racial (desconfiança e preconceito generalizados)",
      "Relações neutras (nenhuma animosidade ou cooperação significativa)",
    ],
  },
  RELIGIAO: {
    DEIDADE: [
      "Deus da Cura e da Misericórdia",
      "Deusa da Natureza e da Fertilidade",
      "Deus da Guerra e da Honra",
      "Deusa da Sabedoria e do Conhecimento",
      "Deus da Morte e do Além",
      "Deusa da Magia e dos Feitiços",
      "Deus da Justiça e do Julgamento",
      "Deusa da Caça e da Liberdade",
      "Deus das Tempestades e da Fúria",
      "Deusa do Amor e da Beleza",
      "Deus da Engenharia e da Tecnologia",
      "Deusa da Música e da Criatividade",
      "Deus da Noite e dos Sonhos",
      "Deusa da Vingança e da Retribuição",
      "Deus da Lua e dos Mistérios",
      "Deusa do Sol e da Luz",
      "Deus dos Viajantes e dos Caminhos",
      "Deusa dos Oceanos e das Profundezas",
      "Deus dos Dragões e das Bestas",
      "Deusa do Destino e da Sorte",
    ],
    CRENCA: [
      "Adoração à natureza e aos elementos",
      "Crença na reencarnação e no ciclo da vida",
      "Culto à ancestralidade e veneração dos mortos",
      "Peregrinações a locais sagrados",
      "Oferendas e sacrifícios de animais",
      "Jejum e abstinência em determinados dias",
      "Crença em profecias e visões divinas",
      "Culto a animais sagrados como símbolos divinos",
      "Meditação e busca de iluminação espiritual",
      "Práticas de cura e bênçãos para os doentes",
      "Realização de rituais de purificação",
      "Práticas de magia religiosa e feitiçaria divina",
    ],
    RELACOES: [
      "Relações amistosas e alianças religiosas",
      "Rivalidade saudável com competições religiosas",
      "Coexistência pacífica com interações limitadas",
      "Tensão diplomática com debates religiosos frequentes",
      "Guerra santa ou conflitos religiosos intermitentes",
      "Tratado de não interferência nas crenças alheias",
      "Sincretismo religioso com influência mútua",
      "Perseguição religiosa e tentativas de conversão forçada",
    ],
  },
  CULTURA: {
    VESTIMENTA: [
      "Togas e Sandálias: Vestimenta simples e solta, com sandálias de couro, usada em climas quentes",
      "Quimonos e Obi: Traje japonês tradicional, composto por um quimono e um cinto largo (obi)",
      "Kilts e Tartan: Saias escocesas e mantos de xadrez usados por clãs das Terras Altas",
      "Roupas de Peles e Pêlos: Vestimenta quente feita de peles de animais, adequada para climas frios",
      "Túnicas e Calças Largas: Roupas medievais europeias, incluindo túnicas e calças largas",
      "Saris e Bindis: Vestimenta indiana composta por saris coloridos e bindis na testa",
      "Trajes Beduínos: Roupas tradicionais dos beduínos, incluindo túnicas e lenços na cabeça",
      "Kimonos e Hakama: Traje formal japonês, com um kimono e calças largas (hakama)",
      "Vestimenta Viking: Roupas de lã e couro usadas pelos vikings, incluindo túnicas e mantos",
      "Roupas de Seda e Brocado: Vestimenta luxuosa, feita de seda e enfeitada com brocados, usada em cortes reais",
    ],
    COMIDA: [
      "Carne Assada e Legumes: Um prato de carne assada, acompanhado de legumes cozidos",
      "Sopa de Cogumelos: Uma sopa cremosa feita com uma variedade de cogumelos",
      "Peixe Grelhado com Ervas: Peixe grelhado temperado com ervas frescas",
      "Pão de Mel e Queijo: Pão de mel fresco servido com uma seleção de queijos",
      "Curry de Vegetais: Vegetais cozidos em um molho de curry aromático",
      "Carne de Caça e Frutas: Carne de caça cozida com frutas em um molho adocicado",
      "Ensopado de Feijão e Carne: Feijão cozido com carne e temperos",
      "Assado de Frango e Batatas: Frango assado com batatas e ervas",
      "Espetinhos de Carne e Legumes: Espetinhos grelhados de carne e legumes",
      "Tortas de Frutas: Tortas recheadas com frutas frescas",
      "Cerveja Artesanal: Uma cerveja localmente produzida com sabores únicos",
      "Vinho Especiado: Um vinho aquecido com especiarias para criar uma bebida quente",
    ],
    FESTA: [
      "Festival da Colheita: Uma celebração de agradecimento pelas colheitas bem-sucedidas",
      "Dia dos Mortos: Uma homenagem aos entes queridos falecidos, com rituais e memória",
      "Festival da Luz: Uma celebração de luz e renovação, muitas vezes com lanternas ou velas",
      "Festa do Solstício: Marcando o solstício de inverno ou verão, com atividades sazonais",
      "Carnaval: Um período de festividades, dança e desfiles extravagantes",
      "Dia dos Heróis: Uma homenagem a figuras históricas ou lendárias da cultura local",
      "Feira de Comércio: Um evento onde mercadores de toda a região se reúnem para negociar",
      "Dia da União: Uma celebração da paz e da harmonia entre diferentes grupos",
      "Festival das Artes: Uma celebração das artes, com performances, exposições e competições",
      "Dia do Renascimento: Uma celebração do nascimento de um novo ano, com rituais de renovação",
    ],
  },
  HISTORIA: {
    EVENTO: [
      "Grande Guerra: Uma guerra de grande escala que mudou o curso da história",
      "Ascensão de uma Dinastia: A ascensão de uma nova linhagem real ou governante poderoso",
      "Descoberta de um Continente: A exploração e descoberta de um novo continente ou território",
      "Desastre Natural Catastrófico: Um evento natural devastador, como terremoto, tsunami ou erupção vulcânica",
      "Revolução Popular: Uma revolução que mudou o sistema político ou social do país",
      "Era de Ouro da Arte e Cultura: Um período de grande florescimento artístico e cultural",
      "Invasão de uma Força Maligna: Uma invasão por uma força sombria ou maligna que ameaçou a existência da civilização",
      "Fundação de uma Cidade: A fundação de uma cidade importante ou capital",
      "Descoberta de um Artefato Místico: A descoberta de um artefato místico ou reliquia que mudou a compreensão do mundo",
      "Tratado de Paz Histórico: A assinatura de um tratado que encerrou um longo conflito e estabeleceu a paz duradoura",
    ],
    PERSONALIDADE: [
      "Rei ou Rainha: Um monarca que teve um impacto significativo na história",
      "Explorador: Um aventureiro que mapeou terras desconhecidas",
      "Herói de Guerra: Um líder militar que conduziu seu povo à vitória",
      "Filósofo ou Sábio: Um pensador cujas ideias influenciaram a sociedade",
      "Artista ou Músico: Um criador de obras que deixaram um legado duradouro",
      "Líder Religioso: Um fundador ou líder de uma religião ou seita",
      "Cientista ou Inventor: Um gênio que fez descobertas revolucionárias",
      "Político Visionário: Um líder que promoveu reformas sociais ou políticas",
      "Mercador ou Comerciante: Um empreendedor que expandiu rotas comerciais",
      "Rebelde ou Revolucionário: Um líder que desafiou o status quo",
      "Herói Anônimo: Uma pessoa comum que realizou um ato heróico",
      "Vilão Histórico: Uma figura infame conhecida por suas ações malignas",
    ],
    RELIQUIA: [
      "Espada da Chama Eterna: Uma espada que sempre está em chamas sem se consumir",
      "Colar da Cura: Um colar que pode curar ferimentos quando ativado",
      "Livro das Profecias: Um livro que contém previsões precisas do futuro",
      "Amuleto da Invisibilidade: Um amuleto que concede invisibilidade por um curto período",
      "Caldeirão da Abundância: Um caldeirão que pode produzir comida e água",
      "Pergaminho de Controle Elemental: Um pergaminho que permite controlar elementos naturais",
      "Cajado do Raio: Um cajado que dispara raios poderosos",
      "Máscara da Ilusão: Uma máscara que cria ilusões convincentes",
      "Anel da Ressurreição: Um anel que pode trazer os mortos de volta à vida",
      "Lágrima da Cura: Uma pedra que cura doenças e venenos",
      "Bastão da Teletransporte: Um bastão que permite viajar instantaneamente para locais conhecidos",
      "Olho da Visão Verdadeira: Um olho mágico que revela a verdade por trás das ilusões",
      "Arco da Precisão: Um arco que nunca erra o alvo",
      "Manto da Invisibilidade: Um manto que concede invisibilidade contínua",
      "Cristal de Conhecimento: Um cristal que concede conhecimento instantâneo",
      "Adaga das Sombras: Uma adaga que permite mover-se nas sombras",
      "Chapéu do Controle Animal: Um chapéu que permite controlar animais",
      "Lente da Perspicácia: Uma lente que revela detalhes ocultos",
      "Lápide da Comunicação: Uma lápide que permite falar com os espíritos",
      "Coroa da Imortalidade: Uma coroa que concede imortalidade",
    ],
  },
  POLITICA: {
    GRUPOS: [
      "Partido dos Reformistas: Um grupo que busca reformas políticas e sociais",
      "Liga dos Comerciantes: Uma organização que protege os interesses comerciais",
      "Guardiões da Tradição: Uma facção que valoriza e preserva a cultura antiga",
      "Movimento Libertário: Um grupo que busca a liberdade individual e o menor governo possível",
      "Liga dos Magos: Uma organização de magos que busca influência política",
      "Defensores dos Direitos dos Elfos: Uma facção que luta pelos direitos dos elfos",
      "Clã dos Anões do Subterrâneo: Um clã anão que busca o reconhecimento político",
      "Sociedade Secreta dos Illuminati: Uma organização misteriosa que manipula os bastidores da política",
    ],
    CONFLITOS: [
      "Guerra de Sucessão: Duas ou mais facções disputam o controle de um trono",
      "Conflito de Fronteira: Duas nações estão em disputa territorial",
      "Guerra Religiosa: Diferentes religiões ou seitas estão em conflito",
      "Revolução Popular: Um grupo luta contra um governo opressor",
      "Guerra de Recursos: Disputa por recursos naturais escassos",
      "Conflito Racial: Tensões étnicas ou raciais levam a confrontos",
      "Guerra Civil: Divisões internas resultam em um conflito armado",
      "Conflito de Clãs: Clãs ou famílias rivais lutam pelo poder",
      "Confronto Mágico: Usuários de magia disputam o controle de artefatos poderosos",
      "Conflito com Criaturas: Monstros ou criaturas ameaçam uma região",
    ],
    QUESTOES: [
      "Reforma Tributária: Debate sobre a distribuição de impostos e recursos",
      "Direitos Civis: Questões de igualdade e liberdades individuais",
      "Política Externa: Discussões sobre tratados, alianças e relações internacionais",
      "Segurança Nacional: Preocupações com ameaças externas e defesa do país",
      "Desigualdade de Renda: Debate sobre a disparidade econômica",
      "Meio Ambiente: Questões relacionadas à preservação e sustentabilidade",
      "Saúde Pública: Políticas de assistência médica e cuidados de saúde",
      "Educação: Reformas educacionais e financiamento escolar",
      "Imigração: Questões de controle de fronteira e cidadania",
      "Corrupção: Combate à corrupção no governo e instituições",
      "Religião e Estado: Separação ou fusão de assuntos religiosos e governamentais",
      "Reforma Política: Mudanças na estrutura do governo e do sistema eleitoral",
    ],
  },
  ECOLOGIA: {
    CRIATURA: [
      "Dragão: Uma criatura lendária de grande poder",
      "Fênix: Uma ave mítica que renasce das cinzas",
      "Unicórnio: Uma criatura majestosa com um chifre em espiral",
      "Grifo: Uma besta alada com corpo de leão e cabeça de águia",
      "Hipogrifo: Uma mistura de cavalo e águia, com asas e garras",
      "Basilisco: Uma serpente monstruosa com olhar petrificante",
      "Lobo Gigante: Um lobo de tamanho colossal",
      "Kelpie: Um cavalo das águas com aparência encantadora",
      "Treant: Uma árvore viva com consciência",
      "Fenômeno Espiritual: Uma entidade espectral ou fantasmagórica",
      "Elemental da Terra: Uma criatura feita de rocha ou terra",
      "Fada: Seres mágicos pequenos e etéreos",
    ],
    VEGETACAO_UNICA: [
      "Árvore das Estrelas: Árvore com folhas que brilham como estrelas à noite",
      "Flores Cantoras: Flores que emitem melodias suaves quando acariciadas pelo vento",
      "Herbária da Cura: Plantas medicinais com propriedades curativas",
      "Videira de Espinhos: Uma videira que se move e se defende com espinhos afiados",
      "Árvore Anciã: Uma árvore antiga com sabedoria e poder mágico",
      "Cogumelos Luminosos: Cogumelos que emitem luz suave",
      "Cipós da Serpente: Cipós que se movem como serpentes e podem ser usados para atacar",
      "Planta Carnívora: Uma planta que se alimenta de insetos ou pequenos animais",
      "Raiz da Imortalidade: Uma raiz que dizem conceder vida eterna",
      "Orquídea da Transformação: Uma flor que pode transformar quem a toca",
      "Planta Camaleão: Plantas que mudam de cor para se camuflarem no ambiente",
      "Árvore da Noite Eterna: Uma árvore cujas folhas criam escuridão permanente ao redor",
    ],
    ECOSSISTEMA: [
      "Floresta Encantada: Uma floresta onde as árvores têm rostos e a magia flui livremente",
      "Deserto de Cristal: Um deserto coberto de cristais brilhantes",
      "Pântano das Almas Perdidas: Um pântano assombrado por espíritos inquietos",
      "Cavernas Bioluminescentes: Complexos de cavernas iluminados por fungos bioluminescentes",
      "Vale da Eterna Primavera: Um vale onde a primavera nunca termina",
      "Planalto das Nuvens: Um planalto elevado acima das nuvens, habitado por criaturas aladas",
      "Lago das Maravilhas: Um lago de águas mágicas com propriedades curativas",
      "Geleira Flamejante: Uma geleira que emite calor e fogo",
      "Mar de Areia Vivente: Um vasto deserto de areia que se move como um oceano",
      "Planície de Pedras Preciosas: Uma planície repleta de pedras preciosas",
    ],
  },
  ECONOMIA: {
    RECURSOS: [
      "Minas de Ferro: Depósitos abundantes de minério de ferro",
      "Florestas Exuberantes: Grandes áreas de florestas cheias de madeira de qualidade",
      "Campos Férteis: Terras agrícolas férteis para cultivo de alimentos",
      "Depósitos de Pedras Preciosas: Jazidas de gemas valiosas",
      "Reservas de Petróleo: Depósitos de petróleo bruto",
      "Fontes Termais e Geiseres: Áreas com fontes termais naturais",
      "Minas de Sal: Depósitos subterrâneos de sal",
      "Recursos Mágicos: Regiões com mana mágica abundante ou locais sagrados",
    ],
    SISTEMA: [
      "Sistema de Moeda Metálica: Moedas de ouro, prata e cobre são amplamente usadas",
      "Sistema de Troca de Bens: A economia é baseada na troca direta de mercadorias",
      "Sistema de Moeda de Troca: Os habitantes usam moedas mágicas como forma de pagamento",
      "Sistema de Comércio de Escambo: Itens valiosos, como gemas, são usados como moeda",
      "Sistema de Crédito Mercantil: Os comerciantes emitem notas de crédito como forma de pagamento",
      "Sistema de Serviços e Favores: Os serviços e favores são usados como meio de troca",
    ],
  },
  TECNOLOGIA: {
    NIVEL: [
      "Idade das Trevas: Tecnologia limitada, com a maioria das pessoas vivendo em comunidades agrárias e pouca compreensão de máquinas ou eletricidade",
      "Era Medieval: Sociedades agrárias e feudalismo predominante, com algumas inovações tecnológicas, como a pólvora e moinhos de vento",
      "Era Renascentista: Um período de crescimento tecnológico, com invenções como a imprensa e o telescópio",
      "Era Industrial: Avanços significativos na tecnologia, incluindo a máquina a vapor e a eletricidade, com o início da Revolução Industrial",
      "Era Moderna: Sociedades altamente tecnológicas, com comunicação global, eletrônicos e viagens espaciais",
      "Era Futurista: Tecnologia avançada e futurista, incluindo inteligência artificial, viagens interplanetárias e avanços em biotecnologia",
    ],
    MAGIA: [
      "Magia Arcana: Uso de fórmulas e gestos para lançar feitiços",
      "Magia Divina: Magia concedida por deidades ou entidades divinas",
      "Magia Elemental: Manipulação dos elementos naturais (fogo, água, terra, ar)",
      "Magia Rúnica: Uso de runas ou símbolos mágicos para canalizar poderes",
      "Magia Psíquica: Controle mental, leitura de mentes e poderes psíquicos",
      "Magia Xamânica: Conexão com espíritos e natureza para obter poderes mágicos",
      "Magia Necromântica: Manipulação de morte e energia vital",
      "Magia Alquímica: Uso de poções e substâncias alquímicas para efeitos mágicos",
      "Magia Musical: Magia ativada por instrumentos musicais ou canções",
      "Magia do Caos: Uso imprevisível de magia, muitas vezes com efeitos aleatórios",
    ],
  },
};
